SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;


INSERT INTO cfg_categories VALUES (1, 'government');
INSERT INTO cfg_categories VALUES (2, 'hacking');
INSERT INTO cfg_categories VALUES (3, 'hobby');
INSERT INTO cfg_categories VALUES (4, 'homestyle');
INSERT INTO cfg_categories VALUES (5, 'hospitals');
INSERT INTO cfg_categories VALUES (6, 'imagehosting');
INSERT INTO cfg_categories VALUES (7, 'isp');
INSERT INTO cfg_categories VALUES (8, 'jobsearch');
INSERT INTO cfg_categories VALUES (9, 'library');
INSERT INTO cfg_categories VALUES (10, 'military');
INSERT INTO cfg_categories VALUES (11, 'models');
INSERT INTO cfg_categories VALUES (12, 'movies');
INSERT INTO cfg_categories VALUES (13, 'music');
INSERT INTO cfg_categories VALUES (14, 'news');
INSERT INTO cfg_categories VALUES (15, 'podcasts');
INSERT INTO cfg_categories VALUES (16, 'politics');
INSERT INTO cfg_categories VALUES (17, 'porn');
INSERT INTO cfg_categories VALUES (18, 'radiotv');
INSERT INTO cfg_categories VALUES (19, 'recreation');
INSERT INTO cfg_categories VALUES (20, 'redirector');
INSERT INTO cfg_categories VALUES (21, 'religion');
INSERT INTO cfg_categories VALUES (22, 'remotecontrol');
INSERT INTO cfg_categories VALUES (23, 'ringtones');
INSERT INTO cfg_categories VALUES (24, 'science');
INSERT INTO cfg_categories VALUES (25, 'searchengines');
INSERT INTO cfg_categories VALUES (26, 'sex');
INSERT INTO cfg_categories VALUES (27, 'shopping');
INSERT INTO cfg_categories VALUES (28, 'socialnet');
INSERT INTO cfg_categories VALUES (29, 'spyware');
INSERT INTO cfg_categories VALUES (30, 'tracker');
INSERT INTO cfg_categories VALUES (31, 'updatesites');
INSERT INTO cfg_categories VALUES (32, 'urlshortener');
INSERT INTO cfg_categories VALUES (33, 'violence');
INSERT INTO cfg_categories VALUES (34, 'warez');
INSERT INTO cfg_categories VALUES (35, 'weapons');
INSERT INTO cfg_categories VALUES (36, 'webmail');
INSERT INTO cfg_categories VALUES (37, 'webphone');
INSERT INTO cfg_categories VALUES (38, 'webradio');
INSERT INTO cfg_categories VALUES (39, 'webtv');
INSERT INTO cfg_categories VALUES (40, 'adv');
INSERT INTO cfg_categories VALUES (41, 'aggressive');
INSERT INTO cfg_categories VALUES (42, 'alcohol');
INSERT INTO cfg_categories VALUES (43, 'anonvpn');
INSERT INTO cfg_categories VALUES (44, 'automobile');
INSERT INTO cfg_categories VALUES (45, 'chat');
INSERT INTO cfg_categories VALUES (46, 'costtraps');
INSERT INTO cfg_categories VALUES (47, 'dating');
INSERT INTO cfg_categories VALUES (48, 'downloads');
INSERT INTO cfg_categories VALUES (49, 'drugs');
INSERT INTO cfg_categories VALUES (50, 'dynamic');
INSERT INTO cfg_categories VALUES (51, 'education');
INSERT INTO cfg_categories VALUES (52, 'finance');
INSERT INTO cfg_categories VALUES (53, 'fortunetelling');
INSERT INTO cfg_categories VALUES (54, 'forum');
INSERT INTO cfg_categories VALUES (55, 'gamble');
