CREATE ROLE inkquerier;
ALTER ROLE inkquerier WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION CONNECTION LIMIT 75 PASSWORD 'PASS1' VALID UNTIL 'infinity';
CREATE ROLE inkupdater;
ALTER ROLE inkupdater WITH SUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION CONNECTION LIMIT 2 PASSWORD 'PASS2' VALID UNTIL 'infinity';
